"""
Core data models for Easycode orchestrator.

All models use Pydantic v2 for validation and serialization.
"""

from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator


class TaskStatus(str, Enum):
    """Task lifecycle status."""

    PENDING = "pending"
    PLANNED = "planned"
    RUNNING = "running"
    DONE = "done"
    FAILED = "failed"
    MERGED = "merged"
    CANCELLED = "cancelled"


class AgentType(str, Enum):
    """Supported agent types."""

    CLAUDE_CLI = "claude-cli"
    CODEX_CLI = "codex-cli"
    GEMINI_CLI = "gemini-cli"
    MOCK = "mock"


class AgentConfig(BaseModel):
    """Configuration for an agent adapter."""

    model_config = ConfigDict(extra="forbid")

    type: AgentType
    enabled: bool = True
    command: list[str] = Field(default_factory=list)
    timeout: int = 600  # seconds, 0 = no timeout
    env: dict[str, str] = Field(default_factory=dict)

    # Mock agent specific
    simulate_delay: bool = True
    min_delay: float = 0.5
    max_delay: float = 2.0


class Workspace(BaseModel):
    """Represents the main workspace context."""

    model_config = ConfigDict(extra="forbid")

    path: Path
    current_branch: str
    worktree_dir: Path
    log_dir: Path
    state_dir: Path

    @field_validator("path", "worktree_dir", "log_dir", "state_dir", mode="before")
    @classmethod
    def resolve_path(cls, v: Any) -> Path:
        """Resolve paths to absolute."""
        if isinstance(v, str):
            return Path(v).resolve()
        if isinstance(v, Path):
            return v.resolve()
        return v


class WorktreeSession(BaseModel):
    """Represents a git worktree session for an agent task."""

    model_config = ConfigDict(extra="forbid")

    id: str
    path: Path
    branch: str
    task_id: str
    agent_id: str
    created_at: datetime = Field(default_factory=datetime.now)
    is_active: bool = True
    output_commit: Optional[str] = None  # Commit hash after task completion
    commit_message: Optional[str] = None  # Commit message

    @field_validator("path", mode="before")
    @classmethod
    def resolve_path(cls, v: Any) -> Path:
        if isinstance(v, str):
            return Path(v).resolve()
        if isinstance(v, Path):
            return v.resolve()
        return v


class Task(BaseModel):
    """Represents a single task to be executed by an agent."""

    model_config = ConfigDict(extra="forbid")

    id: str
    title: str
    description: str
    prompt: str  # The actual instruction for the agent
    status: TaskStatus = TaskStatus.PENDING
    assigned_agent: Optional[str] = None
    worktree: Optional[WorktreeSession] = None
    depends_on: list[str] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=datetime.now)
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    result_summary: Optional[str] = None
    error_message: Optional[str] = None
    metadata: dict[str, Any] = Field(default_factory=dict)

    def can_run(self) -> bool:
        """Check if all dependencies are satisfied."""
        return self.status == TaskStatus.PENDING or self.status == TaskStatus.PLANNED


class RunResult(BaseModel):
    """Result of an agent task execution."""

    model_config = ConfigDict(extra="forbid")

    task_id: str
    agent_id: str
    success: bool
    summary: str
    stdout: str = ""
    stderr: str = ""
    exit_code: int = 0
    changed_files: list[str] = Field(default_factory=list)
    diff: str = ""
    duration_seconds: float = 0.0
    started_at: datetime = Field(default_factory=datetime.now)
    completed_at: Optional[datetime] = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class Plan(BaseModel):
    """A plan generated by the mentor agent."""

    model_config = ConfigDict(extra="forbid")

    id: str
    goal: str
    tasks: list[Task]
    created_at: datetime = Field(default_factory=datetime.now)
    mentor_agent: str
    context: str = ""  # Additional context provided by mentor


class AppConfig(BaseModel):
    """Application configuration loaded from TOML."""

    model_config = ConfigDict(extra="forbid")

    workspace: Workspace
    mentor: dict[str, Any] = Field(default_factory=lambda: {"agent": "claude-cli", "max_concurrent": 3})
    agents: dict[str, AgentConfig] = Field(default_factory=dict)
    verify: dict[str, Any] = Field(default_factory=lambda: {"commands": []})
    ui: dict[str, Any] = Field(default_factory=lambda: {"theme": "dark", "refresh_rate": 30})
    logging: dict[str, Any] = Field(default_factory=lambda: {"level": "INFO"})


class AppState(BaseModel):
    """Global application state."""

    model_config = ConfigDict(extra="forbid")

    current_plan: Optional[Plan] = None
    tasks: dict[str, Task] = Field(default_factory=dict)
    worktrees: dict[str, WorktreeSession] = Field(default_factory=dict)
    results: dict[str, RunResult] = Field(default_factory=dict)
    active_agents: dict[str, str] = Field(default_factory=dict)  # agent_id -> task_id
    mentor_agent: str = "claude-cli"

    def get_task(self, task_id: str) -> Optional[Task]:
        """Get a task by ID."""
        return self.tasks.get(task_id)

    def get_pending_tasks(self) -> list[Task]:
        """Get all pending tasks."""
        return [t for t in self.tasks.values() if t.status == TaskStatus.PENDING]

    def get_running_tasks(self) -> list[Task]:
        """Get all running tasks."""
        return [t for t in self.tasks.values() if t.status == TaskStatus.RUNNING]

    def get_completed_tasks(self) -> list[Task]:
        """Get all completed tasks (done or merged)."""
        return [t for t in self.tasks.values() if t.status in (TaskStatus.DONE, TaskStatus.MERGED)]